version: "3.9"

services:
  redis:
    image: redis:8-alpine
    container_name: workflow-lab-redis

    ports:
      - "6380:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: workflow-lab-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis-data: